apiVersion: v1
kind: Service
metadata:
  name: kafka

spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      name: plaintext
      targetPort: 9092
    - port: 9094
      name: external
      targetPort: 9094
