server:
  port: 8000

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    consumer:
      group-id: "bot-1"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false

topic:
  producer:
    metric: send-telegram-to-metric-event
    car: send-telegram-to-car-save-event
    state: send-telegram-to-bot-state-event


bot:
  username: my_awesome_car_bot
  token: 2070228409:AAH5sOZ_tbstAwYTIVSoxjI8z26UtL639DA
  webHookPath: ${WEB_HOOK}
  api:
    baseurlForCarService: ${CAR_SERVICE_BASE_URL}
    baseurlForMetricService: ${METRIC_SERVICE_BASE_URL}
    baseurlForBotStateService: ${BOT_STATE_SERVICE_BASE_URL}
    subPath:
      car-handler: api/car
      bot-state: api/botState
      cost-handler: api/costs
      metrics: api/metrics

buttons:
  callback:
    statistics: '{
       mileage: "button.mileage",
       gas:  "button.gas",
       spares: "button.spares"
    }'
    transmission: '{
        mechanical: "transmission.mechanic",
        automatic: "transmission.automate",
        robot: "transmission.robot"
    }'
  keyboard:
    main-menu:
      'button.my.car,
       button.my.costs,
       button.my.statistics'
    costs-menu:
      'button.mileage,
       button.gas,
       button.spares,
       button.back.to.main.menu'
    car-menu:
      'button.register.car,
       button.car.inform,
       button.back.to.main.menu'
    car-maintenance:
      'button.total,
       button.remind,
       button.service.mileage,
       button.maintenance.info,
       button.back.to.settings.menu'